Update AttachDocumentsforViewers
kanboard/website pull request #136
Opened 2019-01-16 16:36 UTC by hernandezfo

Update AttachDocumentsforViewers. Issues Fixed. New version 0.0.2

[AttachDocumentsforViewers-0.0.2.zip](https://github.com/kanboard/website/files/2765130/AttachDocumentsforViewers-0.0.2.zip)

[SourceCode-AttachDocumentsforViewers-0.0.2.zip](https://github.com/kanboard/website/files/2765132/SourceCode-AttachDocumentsforViewers-0.0.2.zip)

2019-01-16 19:01 UTC, creecros commented
Your attached zips still show version 0.0.1 in Plugin.php.

You need to place these in your repo, either in the repo file directory or as a [release](https://github.com/hernandezfo/AttachDocumentsforViewers/releases). Then update the download link in the json, as well.

```php
 "download": "https://github.com/hernandezfo/AttachDocumentsforViewers/releases/download/0.0.2/AttachDocumentsforViewers-0.0.2.zip",
```

2019-01-17 00:11 UTC, hernandezfo commented
Repository and json updated

2019-01-17 01:45 UTC, creecros commented
That's a dead download link until you draft new release with the 0.0.2 tag.

2019-01-20 18:28 UTC, fguillot requested changes

2019-01-20 18:28 UTC, fguillot commented on plugins.json
> +        "download": "https://github.com/hernandezfo/AttachDocumentsforViewers/releases/download/0.0.2/AttachDocumentsforViewers-0.0.2.zip",
This link returns a 404.

2019-02-20 02:07 UTC, fguillot commented
Closing stale PR after 1 month of inactivity.

2019-02-20 02:07 UTC, closed without merging