Added a new theme for Kanboard - ThemeMaestro
kanboard/website pull request #395
Opened 2023-01-03 17:12 UTC by JustFxDev

2023-01-03 19:50 UTC, aljawaid requested changes
Look into the file structure and the download link

2023-01-03 19:50 UTC, aljawaid commented on plugins.json
> +        "download": "https://github.com/JustFxDev/ThemeMaestro/blob/main/release/v0.7.0/ThemeMaestro.zip",
I'm not sure if this link will install or parse correctly as opening it should trigger a download, but instead it goes to the GitHub page.

I think the file structure is wrong for this plugin. Check the structure in the readme of this repository.

2023-01-04 12:56 UTC, aljawaid approved these changes
This link looks fine now, but the plugin file structure still seems wrong, but if it works it works.

2023-01-04 13:06 UTC, aljawaid commented on plugins.json
> +        "download": "https://github.com/JustFxDev/ThemeMaestro/raw/main/release/v0.7.0/ThemeMaestro.zip",
I would have used this link, but if yours works, it works.

`https://github.com/JustFxDev/ThemeMaestro/releases/download/v0.7.0/ThemeMaestro_v0.7.0.zip`

2023-01-05 18:34 UTC, JustFxDev commented
> This link looks fine now, but the plugin file structure still seems wrong, but if it works it works.

There is no file structure. Just the main folder and some files in that one. It's a theme. 

For sure i can put the css in subfolders but i think this is not neccessary.

Is there something else to do? I saw it hast not been pulled.

2023-01-05 18:52 UTC, aljawaid commented
I think the subfolders matter for updating all versions.

2023-01-05 19:11 UTC, JustFxDev commented
> I think the subfolders matter for updating all versions.

Sorry, i do not understand what this means. If the archive is unpacked to .\plugins one gets

```
.\plugins\ThemeMaestro\ThemeMaestro.css
.\plugins\ThemeMaestro\blue.css
.\plugins\ThemeMaestro\column_colors_multi.css
.\plugins\ThemeMaestro\column_colors_none.css
.\plugins\ThemeMaestro\green.css
.\plugins\ThemeMaestro\LICENSE
.\plugins\ThemeMaestro\Plugin.php
.\plugins\ThemeMaestro\README.md
.\plugins\ThemeMaestro\red.css
 ```
 containing all the files.
 
 Same as e. g. in the WekanBoard Theme.
 
 Please let me know what is expected here. I simply do not get it.

2023-01-05 19:17 UTC, aljawaid commented
> > I think the subfolders matter for updating all versions.
> 
> Sorry, i do not understand what this means. If the archive is unpacked to .\plugins one gets
> 
> ```
> .\plugins\ThemeMaestro\ThemeMaestro.css
> .\plugins\ThemeMaestro\blue.css
> .\plugins\ThemeMaestro\column_colors_multi.css
> .\plugins\ThemeMaestro\column_colors_none.css
> .\plugins\ThemeMaestro\green.css
> .\plugins\ThemeMaestro\LICENSE
> .\plugins\ThemeMaestro\Plugin.php
> .\plugins\ThemeMaestro\README.md
> .\plugins\ThemeMaestro\red.css
> ```
> 
> containing all the files.
> 
> Same as e. g. in the WekanBoard Theme.
> 
> Please let me know what is expected here. I simply do not get it.

add me to your repository

2023-01-05 19:20 UTC, JustFxDev commented
> add me to your repository

done

2023-01-05 19:23 UTC, aljawaid commented
close this pull request, let me clean up the structure and then we can do another pull request

2023-01-05 19:25 UTC, closed without merging