Added CardPushDate plugin
kanboard/website pull request #59
Opened 2018-08-31 17:30 UTC by dmorlitz

Added a plugin which puts quick action buttons on task cards, including pushing due date out, view last comment, edit, close and move cards.

2018-09-01 01:09 UTC, fguillot requested changes

2018-09-01 01:09 UTC, fguillot commented on plugins.json
> +        "download": "https://github.com/dmorlitz/kanboard-CardPushDate/archive/CardPushDate.zip",
Please, follow the instructions to build the archive: https://github.com/kanboard/website#how-to-add-a-new-plugin-to-the-list

2018-09-01 14:12 UTC, dmorlitz commented
I believe I have rebuilt the necessary ZIP files based on the instructions you sent.  I have updated the ZIP files on my previous plugins as well as fixed the new plugin description in this pull request.

Please let me know if I missed something or made a mistake.

2018-09-02 03:00 UTC, merged

2018-09-02 03:00 UTC, fguillot commented
LGTM 👍