update coverimage
kanboard/website pull request #73
Opened 2018-10-05 17:48 UTC by BlueTeck

2018-10-05 18:05 UTC, creecros commented on plugins.json
>          "version": "1.0.38.1",
"version": "1.2.5",

2018-10-05 18:10 UTC, creecros commented on plugins.json
> +        "compatible_version": ">=1.2.5"
"compatible_version": ">=1.0.38" should still be valid

2018-10-05 18:22 UTC, creecros requested changes
Few edits

2018-10-06 11:44 UTC, BlueTeck commented
thanks, changed

2018-10-06 19:45 UTC, merged